apiVersion: v1
kind: Template
metadata:
  name: demo
  annotations:
    description: "Description"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: VASE-IMAGE
    name: VASE-IMAGE
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deploymentconfig: VASE-IMAGE
- apiVersion: v1
  kind: Route
  id: demo-http
  metadata:
    name: demo-route
  spec:
    port:
      targetPort: 5000-tcp
    to:
      kind: Service
      name: VASE-IMAGE
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: VASE-IMAGE
    name: VASE-IMAGE
  spec:
    replicas: 1
    selector:
      app: VASE-IMAGE
      deploymentconfig: VASE-IMAGE
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: VASE-IMAGE
          deploymentconfig: VASE-IMAGE
      spec:
        containers:
        - image: rwngwn/demo@sha256:869685df178003550ef72a05834bcac6f763369b16868dfb3141c3ce48c0aec6
          imagePullPolicy: Always
          name: VASE-IMAGE
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - VASE-IMAGE
        from:
          kind: ImageStreamTag
          name: VASE-IMAGE:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      app: VASE-IMAGE
      openshift.io/deployment-config.name: VASE-IMAGE
    name: VASE-IMAGE-1
  spec:
    replicas: 1
    selector:
      app: VASE-IMAGE
      deployment: VASE-IMAGE-1
      deploymentconfig: VASE-IMAGE
    template:
      metadata:
        labels:
          app: VASE-IMAGE
          deployment: VASE-IMAGE-1
          deploymentconfig: VASE-IMAGE
      spec:
        containers:
        - image: rwngwn/demo@sha256:869685df178003550ef72a05834bcac6f763369b16868dfb3141c3ce48c0aec6
          imagePullPolicy: Always
          name: VASE-IMAGE
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30

